# Generated by Django 5.1.4 on 2025-01-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_about_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feture_image',
            field=models.ImageField(default='path/to/default_image.jpg', upload_to='images'),
        ),
    ]
