# Generated by Django 5.1.4 on 2025-01-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_feture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feture_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
