# Generated by Django 5.1.4 on 2025-01-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_feture_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Main_content',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
