# Generated by Django 5.1.4 on 2025-01-20 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_post_category_alter_about_intro_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
