# Generated by Django 5.1.4 on 2025-01-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_delete_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='category',
        ),
    ]
