# Generated by Django 5.1.4 on 2025-01-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_rename_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feture_image',
            field=models.ImageField(upload_to='Images'),
        ),
    ]
