# Generated by Django 5.1.4 on 2025-01-23 01:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_post_feture_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.AlterField(
            model_name='about',
            name='intro',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
